Sprint 6 solution
SamuelichSam/java-kanban pull request #3
Opened 2024-09-18 20:36 UTC by SamuelichSam

2024-09-19 18:26 UTC, NikolaiDem requested changes

2024-09-19 18:26 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
>      }
При удалении таски по id или всех тасок нужно удалять их и из истории. 
Аналогично для эпиков и сабтасок

2024-09-20 12:45 UTC, SamuelichSam commented
Упустил очевидный момент с удалением из истории) Исправил и добавил тест на удаление задач

2024-09-21 10:27 UTC, NikolaiDem approved these changes

2024-09-21 12:10 UTC, merged