ФЗ 7го спринта, 1-я итерация
SamuelichSam/java-kanban pull request #4
Opened 2024-10-14 20:33 UTC by SamuelichSam

2024-10-15 20:54 UTC, NikolaiDem requested changes

2024-10-15 20:54 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +    private static String toString(Task task) {
Лучше сделать 3 отдельных метода

2024-10-15 20:54 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +        save();
Может быть сначала нужно выполнить действие, а потом сохранить?
Аналогично для всех методов

2024-10-15 20:54 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +public class FileBackedTaskManagerTest {
Нужен тест, где файловый менеджер создается из непустого файла

2024-10-15 20:54 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +    public void save() {
private

2024-10-18 01:22 UTC, NikolaiDem requested changes

2024-10-18 01:22 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +        return newSubtask;
Нужно вернуть объект, который получился в процессе выполнения метода, а не был передан в качестве аргумента
Аналогично для всех методов

2024-10-18 01:22 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +        return updateEpic(epic);
Зачем повторно вызывать update?

2024-10-18 01:22 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +    public void saveForTests() {
Метод не нужен

2024-10-18 01:22 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +        return getTaskById(id);
get не нужен
Аналогично ниже

2024-10-18 01:22 UTC, NikolaiDem commented on src/managers/FileBackedTaskManager.java
> +    public List<Task> getHistory() {
Переопределение дублирует метод родителя

2024-10-18 01:22 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +    public void managerShouldLoadFromFileSavedTask() throws IOException {
Почему не работает такой тест?
 @Test
    public void managerShouldLoadFromFileSavedTask() throws IOException {
        Task task = new Task(0, "Задача-1", "Описание-1", Status.NEW);
        Epic epic = new Epic(1, "Эпик-1", "Описание-1");
        Subtask subtask = new Subtask(2, "Подзадача-1", "Описание-1", Status.NEW, 1);
        List<String> lines = new ArrayList<>();
        lines.add("id,type,name,status,description,epic");
        lines.add(task.toString());
        lines.add(epic.toString());
        lines.add(subtask.toString());
        Files.write(file.toPath(), lines);

        FileBackedTaskManager loadedManager = FileBackedTaskManager.loadFromFile(file);
        loadedManager.addNewTask(new Task(10, "Задача-10", "Описание-1", Status.NEW));

        Assertions.assertEquals(task, loadedManager.getTaskById(0), "Задача не прочиталась из файла");
        Assertions.assertEquals(task.getName(), loadedManager.getTaskById(0).getName(), "Название таски не совпадает");
        Assertions.assertEquals(epic, loadedManager.getEpicById(1), "Задача не прочиталась из файла");
        Assertions.assertEquals(subtask, loadedManager.getSubtaskById(2), "Задача не прочиталась из файла");
    }

2024-10-18 20:34 UTC, SamuelichSam commented on test/FileBackedTaskManagerTest.java
> +        Assertions.assertEquals(task.getName(), loadedManager.getTaskById(0).getName(), "Название задачи не совпадает");
Тесты классная штука. Всплыли ошибки, допущенные еще в прошлых спринтах)

2024-10-19 13:47 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +        Assertions.assertEquals(task.getName(), loadedManager.getTaskById(0).getName(), "Название задачи не совпадает");
it's true

2024-10-19 22:35 UTC, NikolaiDem requested changes

2024-10-19 22:35 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
> +        if (newTask.getId() == null || tasks.containsKey(newTask.getId())) {
Можно сделать метод newTask.isInitialized()

2024-10-19 22:35 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +    public void managerShouldLoadFromFileSavedTask() throws IOException {
А почему не работает такой тест?

```java

```    @Test
    public void managerShouldLoadFromFileSavedTask2() throws IOException {
        Task task = new Task(0, "Задача-1", "Описание-1", Status.NEW);
        Epic epic = new Epic(1, "Эпик-1", "Описание-1");
        Subtask subtask = new Subtask(2, "Подзадача-1", "Описание-1", Status.NEW, 1);
        List<String> lines = new ArrayList<>();
        lines.add("id,type,name,status,description,epic");
        lines.add(task.toString());
        lines.add(epic.toString());
        lines.add(subtask.toString());
        Files.write(file.toPath(), lines);

        FileBackedTaskManager loadedManager = FileBackedTaskManager.loadFromFile(file);
        loadedManager.addNewTask(new Task(null, "Задача-10", "Описание-10", Status.NEW));

        Assertions.assertEquals(task, loadedManager.getTaskById(0), "Задача не прочиталась из файла");
        Assertions.assertEquals(epic, loadedManager.getEpicById(1), "Задача не прочиталась из файла");
        Assertions.assertEquals(subtask, loadedManager.getSubtaskById(2), "Задача не прочиталась из файла");
        Assertions.assertEquals(task.getName(), loadedManager.getTaskById(0).getName(), "Название задачи не совпадает");
        Assertions.assertEquals(epic.getName(), loadedManager.getEpicById(1).getName(), "Название задачи не совпадает");
        Assertions.assertEquals(subtask.getName(), loadedManager.getSubtaskById(2).getName(), "Название задачи не совпадает");
    }

2024-10-20 22:37 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
> +        Integer newId = generateNewId();
В случае проинициализированной таски генерацию id можно не выполнять, конечно

2024-10-20 22:37 UTC, NikolaiDem approved these changes

2024-10-21 03:24 UTC, merged

2024-10-21 06:24 UTC, SamuelichSam commented on src/managers/InMemoryTaskManager.java
> +        Integer newId = generateNewId();
Исправлю