Sprint 8 solution time and duration
SamuelichSam/java-kanban pull request #6
Opened 2024-11-27 16:57 UTC by SamuelichSam

2024-11-27 18:01 UTC, NikolaiDem requested changes

2024-11-27 18:01 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
> +        if (checkCrossing(updatedTask)) {
Ведь при такой проверке обновляющая таска будет проверяться с обновляемой?
Аналогично для сабтасок

2024-11-28 18:15 UTC, SamuelichSam commented on src/managers/InMemoryTaskManager.java
> +    public boolean checkCrossing(Task task) {
Исправил

2024-11-28 18:16 UTC, SamuelichSam commented on src/managers/InMemoryTaskManager.java
>      public Subtask updateSubtask(Subtask updatedSubtask) {
Экспериментировал и забыл удалить. Исправил

2024-11-28 20:14 UTC, SamuelichSam commented on src/managers/InMemoryTaskManager.java
> +        if (checkCrossing(updatedTask)) {
Исправил и сделал тест на проверку ошибок пересечения по времени при обновлении задач

2024-11-29 15:25 UTC, NikolaiDem approved these changes

2024-11-29 15:25 UTC, NikolaiDem commented on src/managers/InMemoryTaskManager.java
> +            Task updatedTask2 = tasks.get(updatedTask.getId());
Цифры в названии переменных не сильно информативны

2024-11-29 16:02 UTC, merged

2024-11-29 16:06 UTC, SamuelichSam commented on src/managers/InMemoryTaskManager.java
> +            Task updatedTask2 = tasks.get(updatedTask.getId());
Названия изменил