Sprint 9 solution http api
SamuelichSam/java-kanban pull request #7
Opened 2024-12-20 20:08 UTC by SamuelichSam

2024-12-21 23:22 UTC, NikolaiDem requested changes

2024-12-21 23:22 UTC, NikolaiDem commented on src/adapters/LocalDateTimeAdapter.java
> +        return LocalDateTime.parse(jsonReader.nextString(), dtf);
А если будет null?

2024-12-21 23:22 UTC, NikolaiDem commented on src/handlers/BaseHttpHandler.java
> +            h.close();
Лучше использовать try with resources для закрытия HttpExchange

2024-12-21 23:22 UTC, NikolaiDem commented on src/handlers/EpicHandler.java
> +            taskManager.addNewEpic(epic);
А обновление эпика?

2024-12-21 23:22 UTC, NikolaiDem commented on src/handlers/SubtaskHandler.java
> +            sendNotFound(exchange);
Если не удалось распарсить id, то это больше похоже на bad request

2024-12-21 23:22 UTC, NikolaiDem commented on test/HttpHistoryTest.java
> +        URI url = URI.create("http://localhost:8080/tasks/" + task.getId());
Конфигурацию сервера лучше вынести в методы инициализации Before

2024-12-21 23:22 UTC, NikolaiDem commented on test/HttpHistoryTest.java
> +        HttpRequest request4 = HttpRequest.newBuilder()
Вместо чисел 1,2,3 и 4 лучше использовать описания этих uri

2024-12-21 23:22 UTC, NikolaiDem commented on test/TaskManagerTest.java
> +        Assertions.assertTrue(exception, "Подзадача не может быть создана без Эпика");
Для проверки исключений лучше использовать методы assertThrows(...)

2024-12-22 11:21 UTC, SamuelichSam commented on src/handlers/SubtaskHandler.java
> +            sendNotFound(exchange);
Исправил

2024-12-22 11:43 UTC, SamuelichSam commented on test/TaskManagerTest.java
> +        Assertions.assertTrue(exception, "Подзадача не может быть создана без Эпика");
Исправил

2024-12-22 11:44 UTC, SamuelichSam commented on src/adapters/DurationAdapter.java
> +        return Duration.ofMinutes(Long.parseLong(jsonReader.nextString()));
Добавил проверку на null

2024-12-22 11:45 UTC, SamuelichSam commented on src/adapters/LocalDateTimeAdapter.java
> +        return LocalDateTime.parse(jsonReader.nextString(), dtf);
Добавил проверку на null

2024-12-22 12:07 UTC, SamuelichSam commented on src/handlers/EpicHandler.java
> +            taskManager.addNewEpic(epic);
Ориентировался на таблицу из ТЗ. Тоже смутило что в ней нет обновления эпика, но решил делать по ТЗ. В итоге сейчас обновление добавил
![Image](https://github.com/user-attachments/assets/4d1bd974-fb73-4004-a141-911fb1d29170)

2024-12-22 12:51 UTC, SamuelichSam commented on test/HttpHistoryTest.java
> +        HttpRequest request4 = HttpRequest.newBuilder()
Исправил

2024-12-22 13:18 UTC, SamuelichSam commented on test/HttpHistoryTest.java
> +        URI url = URI.create("http://localhost:8080/tasks/" + task.getId());
Не смог понять как вынести все конфигурации. Вынес только клиента

2024-12-23 14:53 UTC, NikolaiDem approved these changes

2024-12-23 14:55 UTC, merged